apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-a-gateway
  namespace: currency-app-a
  annotations:
    iam.gke.io/gcp-service-account: currency-app-a-caller@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: false
