apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-b-engine
  namespace: currency-app-b
  annotations:
    iam.gke.io/gcp-service-account: currency-app-b-telemetry@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: false
