apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency-grafana
  namespace: currency-observability
  annotations:
    iam.gke.io/gcp-service-account: grafana-reader@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: false
