apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: runtime-config
    namespace: risk-system
    behavior: replace
    literals:
      - RISK_REGION=us-east4
      - RISK_CLUSTER=gke-risk-use4
      - SERVICE_VERSION=GIT_SHA
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: app-a-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/risk/app-a
    newTag: GIT_SHA
  - name: app-b-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/risk/app-b
    newTag: GIT_SHA
patches:
  - target:
      kind: Deployment
      name: app-a-gateway-a
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          topology.kubernetes.io/zone: us-east4-a
  - target:
      kind: Deployment
      name: app-a-gateway-b
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          topology.kubernetes.io/zone: us-east4-b
  - target:
      kind: Deployment
      name: app-a-gateway-c
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          topology.kubernetes.io/zone: us-east4-c
  - target:
      kind: Service
      name: app-a-gateway
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cloud.google.com/neg: '{"exposed_ports":{"8080":{"name":"app-a-neg-use4"}}}'
