apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/app-b
images:
  - name: app-b-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/risk/app-b
    newTag: GIT_SHA
