apiVersion: 1

datasources:
  - name: Risk BigQuery
    uid: risk-bigquery
    type: grafana-bigquery-datasource
    access: proxy
    editable: false
    jsonData:
      authenticationType: gce
      defaultProject: schwab-assessment-gke
      processingLocation: US
      MaxBytesBilled: 10485760

  - name: Risk Cloud Monitoring
    uid: risk-cloud-monitoring
    type: stackdriver
    access: proxy
    editable: false
    jsonData:
      authenticationType: gce
      defaultProject: schwab-assessment-gke
      universeDomain: googleapis.com
