apiVersion: 1

datasources:
  - name: Currency BigQuery
    uid: currency-bigquery
    type: grafana-bigquery-datasource
    access: proxy
    editable: false
    jsonData:
      authenticationType: gce
      defaultProject: schwab-assessment-gke
      processingLocation: US
      MaxBytesBilled: 52428800

  - name: Currency Cloud Monitoring
    uid: currency-cloud-monitoring
    type: stackdriver
    access: proxy
    editable: false
    jsonData:
      authenticationType: gce
      defaultProject: schwab-assessment-gke
      universeDomain: googleapis.com
